# ================================================================
# Spark Default Configuration
# ================================================================

# GCS Connector
spark.hadoop.fs.gs.impl                       com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem
spark.hadoop.fs.AbstractFileSystem.gs.impl    com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS
spark.hadoop.google.cloud.auth.service.account.enable  true

# Serializer
spark.serializer                              org.apache.spark.serializer.KryoSerializer

# SQL
spark.sql.extensions                          com.google.cloud.spark.bigquery.BigQuerySparkSessionExtension
# spark.sql.catalog.spark_catalog               com.google.cloud.spark.bigquery.v2.Spark35BigQueryTableProvider

# Streaming checkpoint
spark.sql.streaming.checkpointLocation        /tmp/spark-checkpoints

# UI
spark.ui.enabled                              true
